---
title: "Assignment 5"
author: "Ria Krishna"
format: 
    revealjs:
        theme: simple
        font-size: 80%
transition: fade
---

# Assignment 5 Presentation

### Ria Krishna

**October 10, 2024**

---

## GDP Per Capita

After analyzing the WDI dataset, we can find the countries with the highest GDP per capita. Based on the results, Monaco, Liechtenstein, Luxembourg, Bermuda, and Norway are the top five countries with the highest GDP per capita. This economic indicator implies that these countries tend to have higher rates of income, health, satisfaction, etc.

```{python}
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
wdi = pd.read_csv("/Users/riakrishna/Desktop/EmoryJuniorFall/QTM350/assignment5/wdi.csv")
top_five_gdp = wdi[["country", "gdp_per_capita"]].sort_values(by="gdp_per_capita", ascending = False).head(5)
print(top_five_gdp)
```


```{python}
sns.barplot(x="country", y="gdp_per_capita", data = top_five_gdp)
plt.title("Top 5 Countries by GDP")
plt.xlabel("Country Name")
plt.ylabel("GDP Per Capita")
```


---

## Life Expectancy

Another factor that can be analyzed from the dataset is life expecancy. After sorting the life expectancies by lowest to highest, we can see that Chad, Lesotho, Nigeria, Central African Republic, and South Sudan are the countries with the lowest life expectancy. This might be due to several factors, including socioeconomic development, public health, income inequality, etc.

```{python}
lowest_five_life_expectancy = wdi[["country", "life_expectancy"]].sort_values(by="life_expectancy", ascending = True).head(5)
print(lowest_five_life_expectancy)

```
```{python, echo=false}
plt.figure(figsize=(12,6))
sns.barplot(x="country", y="life_expectancy", data = lowest_five_life_expectancy)
plt.ylim(0,100)
```


---
## Conclusion

Overall, multiple insights can be derived from the dataset. A couple that were focused on for this presentation are GDP per Capita and Life Expectancy. BY analyzing these indicators, we can learn more about different factors within countries. 

